spring:
  application:
    name: sf-loteamentos

  jpa:
    show-sql: ${SHOW_SQL:false}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    username: ${DATASOURCE_USER:neondb_owner}
    password: ${DATASOURCE_PASSWORD:npg_Imzvjc1Uoq7E}
    url: ${DATASOURCE_URL:jdbc:postgresql://ep-icy-butterfly-a563y7h5-pooler.us-east-2.aws.neon.tech/loteamentos-db}
    driverClassName: org.postgresql.Driver

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /